from pathlib import Path
import re
p=Path('dashboard.html');s=p.read_text(encoding='utf-8')
js=r'''<script>/* WINTURBO_CONTENT_CHANNEL_APPROVAL_V46 */
(function(){
 const $=x=>document.getElementById(x),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));let channels=[];
 function mediaType(){const f=$('ideaFormat')?.value||'text';return f==='reel'||f==='video'?'video':f==='image'?'image':'text'}
 async function loadAuthorized(){const u=(await sb.auth.getUser()).data?.user;if(!u)return[];const a=await sb.from('user_publishing_account_access').select('publishing_account_id').eq('user_id',u.id).eq('is_active',true).eq('can_create',true).eq('can_submit_for_approval',true);if(a.error)throw a.error;const ids=(a.data||[]).map(x=>x.publishing_account_id);if(!ids.length)return[];const p=await sb.from('publishing_accounts').select('id,platform,account_name,username,connection_status').in('id',ids).eq('is_active',true).eq('connection_status','connected').in('platform',['telegram','instagram']);if(p.error)throw p.error;return p.data||[]}
 function findHost(){const ready=$('readyPostCopy');return ready?(ready.closest('.card')||ready.parentElement):null}
 function ensure(){const host=findHost();if(!host)return false;let d=$('channelApprovalV46');if(!d){d=document.createElement('div');d.id='channelApprovalV46';d.style='margin-top:16px;padding-top:14px;border-top:1px solid var(--line)';d.innerHTML='<div class="k">SEND FOR POSTING APPROVAL</div><div id="channelApprovalListV46" class="muted small" style="margin-top:8px">Loading authorized publishing accounts…</div><div id="channelApprovalMsgV46" class="muted small" style="margin-top:8px"></div>';host.appendChild(d)}render();return true}
 async function render(){const box=$('channelApprovalListV46');if(!box)return;try{channels=await loadAuthorized();if(!channels.length){box.innerHTML='No connected Telegram or Instagram account is authorized for this user.';return}const selected=$('ideaPublishingAccountV49')?.value;const visible=selected?channels.filter(c=>c.id===selected):channels;const list=visible.length?visible:channels;box.innerHTML=list.map(c=>`<button type="button" class="primary sendApprovalV46" data-id="${c.id}" style="display:inline-block!important;visibility:visible!important;opacity:1!important;margin:4px 6px 4px 0">Send to ${esc(c.account_name)} for ${c.platform==='telegram'?'Telegram':'Instagram'} Approval</button>`).join('')+(channels.length>1&&!selected?'<button type="button" id="sendAllApprovalV46" class="secondary" style="display:inline-block!important;margin:4px 0">Send to ALL Authorized Accounts for Approval</button>':'')}catch(e){box.textContent='Unable to load authorized publishing accounts: '+(e.message||e)}}
 async function submit(c){const u=(await sb.auth.getUser()).data?.user;if(!u)throw new Error('Sign in required');const text=$('ideaDraft')?.value?.trim()||$('readyPostCopy')?.textContent?.trim()||'';if(!text)throw new Error('Generate content first');const media=$('ideaMediaUrl')?.value||null;const r=await sb.from('publishing_queue').insert({platform:c.platform,publishing_account_id:c.id,content_text:text,media_url:media,media_type:mediaType(),status:'draft',created_by:u.id,requested_by:u.id}).select('id').single();if(r.error)throw r.error;return r.data}
 async function send(ids){const m=$('channelApprovalMsgV46');if(m)m.textContent='Sending for approval…';let ok=[],fail=[];for(const c of channels.filter(x=>ids.includes(x.id))){try{await submit(c);ok.push(c.account_name)}catch(e){fail.push(c.account_name+': '+(e.message||e))}}if(m)m.textContent=ok.length?`Sent for approval ✓ ${ok.join(', ')}${fail.length?' · Failed: '+fail.join(' | '):''}`:'Could not send: '+fail.join(' | ')}
 document.addEventListener('click',e=>{const b=e.target.closest?.('.sendApprovalV46');if(b){e.preventDefault();send([b.dataset.id])}else if(e.target?.id==='sendAllApprovalV46'){e.preventDefault();send(channels.map(x=>x.id))}else if(e.target?.dataset?.s==='contentIdeas'){setTimeout(ensure,120)}});
 document.addEventListener('change',e=>{if(e.target?.id==='ideaPublishingAccountV49')render()});
 function init(){ensure();setTimeout(ensure,500);setTimeout(ensure,1500)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();</script>'''
pat=r'<script>/\* WINTURBO_CONTENT_CHANNEL_APPROVAL_V46 \*/.*?</script>'
if re.search(pat,s,flags=re.S): s=re.sub(pat,js,s,count=1,flags=re.S)
else: s=s.replace('</body>',js+'\n</body>',1)
p.write_text(s,encoding='utf-8')