from pathlib import Path
p=Path('dashboard.html');s=p.read_text(encoding='utf-8');M='WINTURBO_CONTENT_CHANNEL_APPROVAL_V46'
if M in s: raise SystemExit(0)
js=r'''<script>/* WINTURBO_CONTENT_CHANNEL_APPROVAL_V46 */
(function(){
 const $=x=>document.getElementById(x),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));let channels=[];
 function mediaType(){const f=$('ideaFormat')?.value||'text';return f==='reel'||f==='video'?'video':f==='image'?'image':'text'}
 async function loadAuthorized(){const u=(await sb.auth.getUser()).data?.user;if(!u)return[];const a=await sb.from('user_publishing_account_access').select('publishing_account_id,can_create,can_submit_for_approval,is_active').eq('user_id',u.id).eq('is_active',true).eq('can_create',true).eq('can_submit_for_approval',true);if(a.error)throw a.error;const ids=(a.data||[]).map(x=>x.publishing_account_id);if(!ids.length)return[];const p=await sb.from('publishing_accounts').select('id,platform,account_name,username,connection_status,is_active').in('id',ids).eq('is_active',true).eq('connection_status','connected').in('platform',['telegram','instagram']);if(p.error)throw p.error;return p.data||[]}
 function ensure(){const ready=$('readyPostCopy');if(!ready||$('channelApprovalV46'))return;let host=ready.closest('.card')||ready.parentElement;const d=document.createElement('div');d.id='channelApprovalV46';d.style='margin-top:16px;padding-top:14px;border-top:1px solid var(--line)';d.innerHTML='<div class="k">SEND FOR POSTING APPROVAL</div><div id="channelApprovalListV46" class="muted small" style="margin-top:8px">Loading your authorized publishing accounts…</div><div id="channelApprovalMsgV46" class="muted small" style="margin-top:8px"></div>';host.appendChild(d);render()}
 async function render(){const box=$('channelApprovalListV46');if(!box)return;try{channels=await loadAuthorized();if(!channels.length){box.innerHTML='No connected Telegram or Instagram accounts are authorized for your user.';return}box.innerHTML=channels.map(c=>`<button class="secondary sendApprovalV46" data-id="${c.id}" style="margin:4px 6px 4px 0">Send for ${c.platform==='telegram'?'Telegram':'Instagram'} Approval · ${esc(c.account_name)}</button>`).join('')+(channels.length>1?'<button id="sendAllApprovalV46" class="primary" style="margin:4px 0">Send to ALL Authorized Accounts for Approval</button>':'')}catch(e){box.textContent='Unable to load authorized publishing accounts: '+(e.message||e)}}
 async function submit(c){const u=(await sb.auth.getUser()).data?.user;if(!u)throw new Error('Sign in required');const text=$('ideaDraft')?.value?.trim()||$('readyPostCopy')?.textContent?.trim()||'';if(!text)throw new Error('Generate content first');const media=$('ideaMediaUrl')?.value||null;const row={platform:c.platform,publishing_account_id:c.id,content_text:text,media_url:media,media_type:mediaType(),status:'draft',created_by:u.id,requested_by:u.id};const r=await sb.from('publishing_queue').insert(row).select('id').single();if(r.error)throw r.error;return r.data}
 async function send(ids){const m=$('channelApprovalMsgV46');m.textContent='Sending for approval…';let ok=[],fail=[];for(const c of channels.filter(x=>ids.includes(x.id))){try{await submit(c);ok.push(c.account_name)}catch(e){fail.push(c.account_name+': '+(e.message||e))}}m.textContent=ok.length?`Sent for approval ✓ ${ok.join(', ')}${fail.length?' · Failed: '+fail.join(' | '):''}`:'Could not send: '+fail.join(' | ')}
 document.addEventListener('click',e=>{const b=e.target.closest?.('.sendApprovalV46');if(b)send([b.dataset.id]);if(e.target?.id==='sendAllApprovalV46')send(channels.map(x=>x.id))});
 async function init(){ensure();setTimeout(ensure,1200)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8')