from pathlib import Path
p=Path('dashboard.html');s=p.read_text(encoding='utf-8');M='WINTURBO_COMPLETE_REGISTRATION_V44'
if M in s: raise SystemExit(0)
js=r'''<script>/* WINTURBO_COMPLETE_REGISTRATION_V44 */
(function(){
 const $=x=>document.getElementById(x);
 function ensure(){const box=document.querySelector('.loginBox');if(!box||$('approvedRegistrationV44'))return;const d=document.createElement('div');d.id='approvedRegistrationV44';d.style='margin-top:12px;padding-top:12px;border-top:1px solid var(--line)';d.innerHTML=`<button id="checkApprovalV44" class="secondary" style="width:100%">Check Approval / Complete Registration</button><div id="registrationFormV44" style="display:none;margin-top:10px"><div class="muted small" style="margin-bottom:8px">If your access request has been approved, create your login password here.</div><input id="registrationEmailV44" type="email" placeholder="Approved email" style="width:100%;margin-bottom:8px"><input id="registrationPasswordV44" type="password" placeholder="Create password (minimum 8 characters)" style="width:100%;margin-bottom:8px"><button id="completeRegistrationV44" style="width:100%">Create Login Account</button><div id="registrationMsgV44" class="muted small" style="margin-top:8px"></div></div>`;box.appendChild(d)}
 async function status(email){const r=await sb.functions.invoke('request-dashboard-access',{body:{action:'status',email}});if(r.error)throw r.error;return r.data?.status||'none'}
 async function check(){const f=$('registrationFormV44'),e=$('registrationEmailV44'),base=$('email');f.style.display='block';if(base?.value&&!e.value)e.value=base.value;const email=(e.value||'').trim().toLowerCase();const m=$('registrationMsgV44');if(!email){m.textContent='Enter the email used for your access request.';return}try{const st=await status(email);if(st==='approved'){m.textContent='Access Approved ✓ Create a password below to activate your login.';$('registrationPasswordV44').focus()}else if(st==='pending')m.textContent='Your request is still awaiting admin approval.';else if(st==='rejected')m.textContent='This access request was not approved.';else m.textContent='No approved access request was found for this email.'}catch(err){m.textContent=err.message||String(err)}}
 async function complete(){const email=($('registrationEmailV44')?.value||'').trim().toLowerCase(),password=$('registrationPasswordV44')?.value||'',m=$('registrationMsgV44');if(!email||password.length<8){m.textContent='Enter your approved email and a password of at least 8 characters.';return}try{const st=await status(email);if(st!=='approved'){m.textContent=st==='pending'?'Approval is still pending.':'This email is not approved for registration.';return}const r=await sb.auth.signUp({email,password});if(r.error)throw r.error;if(r.data?.session){m.textContent='Account activated ✓ You are signed in. Reloading dashboard…';setTimeout(()=>location.reload(),900)}else{m.textContent='Login account created. If email confirmation is enabled, confirm the single registration email, then sign in.'}}catch(err){m.textContent=err.message||String(err)}}
 document.addEventListener('click',e=>{if(e.target?.id==='checkApprovalV44')check();if(e.target?.id==='completeRegistrationV44')complete()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure,{once:true});else ensure();
})();</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8')