from pathlib import Path
p=Path('dashboard.html');s=p.read_text(encoding='utf-8');M='WINTURBO_SIGNUP_APPROVAL_V39'
if M in s: raise SystemExit('v39 present')
card='''<div id="signupApprovalV39" class="card" style="margin-top:14px"><div class="sectionHead"><div><h3>Dashboard Account Requests</h3><div class="muted small">New account requests stay blocked until an admin approves them.</div></div><button id="refreshSignupRequestsV39" class="mini">Refresh</button></div><div id="signupRequestsListV39" style="display:grid;gap:10px;margin-top:12px"><div class="muted">Loading requests…</div></div></div>'''
pos=s.find('</section>',s.find('id="verification"'));s=s[:pos]+card+s[pos:]
js=r'''<script>/* WINTURBO_SIGNUP_APPROVAL_V39 */
(function(){const $=x=>document.getElementById(x);async function load(){const box=$('signupRequestsListV39');if(!box)return;const r=await sb.from('dashboard_access_requests').select('*').eq('status','pending').order('requested_at',{ascending:false});if(r.error){box.innerHTML='<div class="muted">Admin access required to view account requests.</div>';return}box.innerHTML=(r.data||[]).map(x=>`<div class="channelAccessRow" style="grid-template-columns:1fr 130px 100px 100px"><div><b>${x.full_name||x.email}</b><div class="muted small">${x.email} · Requested ${new Date(x.requested_at).toLocaleString()}</div></div><select data-role><option value="viewer">View Only</option><option value="admin">Admin</option></select><button class="mini approveSignupV39" data-id="${x.id}">Approve</button><button class="mini rejectSignupV39" data-id="${x.id}">Reject</button></div>`).join('')||'<div class="muted">No pending account requests.</div>'}
async function review(btn,approve){const row=btn.closest('.channelAccessRow'),role=row?.querySelector('[data-role]')?.value||'viewer';btn.disabled=true;const r=await sb.rpc('review_dashboard_access_request',{p_request_id:btn.dataset.id,p_approve:approve,p_access_level:role});if(r.error){alert(r.error.message);btn.disabled=false;return}await load();window.WinTurboRefreshPendingChannelUsersV38?.()}
document.addEventListener('click',e=>{const a=e.target.closest?.('.approveSignupV39'),r=e.target.closest?.('.rejectSignupV39');if(a)review(a,true);if(r)review(r,false)});$('refreshSignupRequestsV39')?.addEventListener('click',load);window.WinTurboLoadSignupRequestsV39=load;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(load,900),{once:true});else setTimeout(load,900)})();
</script>'''
s=s.replace('</body>',js+'\n</body>',1)
signup=r'''<script>/* signup UI v39 - request only, no Supabase Auth signup */
(function(){function add(){const login=document.querySelector('.loginBox,#loginCard,.login-card,.auth-card');if(!login||document.getElementById('createAccountV39'))return;const d=document.createElement('div');d.id='createAccountV39';d.innerHTML=`<div style="margin-top:14px;text-align:center"><button id="showSignupV39" class="mini">Request Access</button></div><div id="signupFormV39" style="display:none;margin-top:12px;gap:8px"><input id="signupNameV39" placeholder="Full name"><input id="signupEmailV39" type="email" placeholder="Email"><button id="submitSignupV39" class="primary" style="width:100%;margin-top:8px">Submit Access Request</button><div class="muted small" style="margin-top:7px">No password or confirmation email is required at this stage.</div><div id="signupMsgV39" class="muted small" style="margin-top:8px"></div></div>`;login.appendChild(d);document.getElementById('showSignupV39').onclick=()=>document.getElementById('signupFormV39').style.display='grid';document.getElementById('submitSignupV39').onclick=async(e)=>{e.preventDefault();const b=document.getElementById('submitSignupV39'),msg=document.getElementById('signupMsgV39');b.disabled=true;const email=document.getElementById('signupEmailV39').value.trim(),full_name=document.getElementById('signupNameV39').value.trim();if(!email){msg.textContent='Please enter your email.';b.disabled=false;return}msg.textContent='Sending account request…';try{const r=await sb.functions.invoke('request-dashboard-access',{body:{email,full_name}});if(r.error)throw r.error;msg.textContent=r.data?.status==='approved'?'This email is already approved. Please use Log in.':'Account request submitted. An administrator will review it under Verification. No email has been sent.'}catch(err){msg.textContent=err?.message||'Could not submit account request.'}finally{b.disabled=false}}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add,{once:true});else add()})();
</script>'''
s=s.replace('</body>',signup+'\n</body>',1);p.write_text(s,encoding='utf-8')