from pathlib import Path
p=Path('dashboard.html');s=p.read_text(encoding='utf-8');M='WINTURBO_VERIFICATION_CLEANUP_V40'
if M in s: raise SystemExit('v40 present')
js=r'''<script>/* WINTURBO_VERIFICATION_CLEANUP_V40 */
(function(){const $=x=>document.getElementById(x);
function removeOld(){[...document.querySelectorAll('#verification .card')].forEach(c=>{const h=(c.querySelector('h3')?.textContent||'').trim().toLowerCase();if(h==='publishing channel verification')c.remove()})}
async function telegram(){const host=[...document.querySelectorAll('#verification .card')].find(c=>(c.querySelector('h3')?.textContent||'').toLowerCase().includes('telegram connections'));if(!host)return;const r=await sb.from('publishing_accounts').select('id,account_name,username,is_active,connection_status').eq('platform','telegram').eq('is_active',true).order('account_name');const rows=r.data||[],live=rows.filter(x=>x.connection_status==='connected').length;let summary=host.querySelector('.v40tgsummary');if(!summary){summary=document.createElement('div');summary.className='v40tgsummary';host.querySelector('.sectionHead')?.after(summary)}summary.innerHTML=`<div class="statGrid" style="margin:12px 0"><div class="stat"><span>Telegram Channels</span><b>${rows.length}</b></div><div class="stat"><span>Live & Connected</span><b>${live}</b></div><div class="stat"><span>Need Connection</span><b>${rows.length-live}</b></div></div>`;const target=host.querySelector('[id*=telegram][id*=List],.telegramConnectionsGrid,.channelGrid')||host;let box=host.querySelector('.v40tglist');if(!box){box=document.createElement('div');box.className='v40tglist';host.appendChild(box)}box.innerHTML=rows.map(x=>`<div class="channelAccessRow" style="grid-template-columns:1fr 130px"><div><b>${x.account_name}</b><div class="muted small">@${x.username||''}</div></div><span class="badge">${x.connection_status==='connected'?'● Live & Connected':'Needs Connection'}</span></div>`).join('')||'<div class="muted">No Telegram publishing channels configured.</div>'}
async function users(){const card=$('channelUserAccessV37');if(!card)return;let panel=$('userActivationV40');if(!panel){panel=document.createElement('div');panel.id='userActivationV40';panel.style.marginBottom='14px';card.insertBefore(panel,card.children[1]||null)}const r=await sb.from('user_access_grants').select('id,email,user_id,access_level,is_active').order('email');if(r.error){panel.innerHTML='<div class="muted">Admin access required.</div>';return}panel.innerHTML='<div class="small" style="font-weight:700;margin-bottom:8px">Users — Activate / Deactivate</div>'+((r.data||[]).map(x=>`<div class="channelAccessRow" style="grid-template-columns:1fr 120px 120px"><div><b>${x.email}</b><div class="muted small">${x.access_level}${x.user_id?'':' · Awaiting Login'}</div></div><span class="badge">${x.is_active?'Active':'Deactivated'}</span><button class="mini toggleUserV40" data-id="${x.id}" data-active="${x.is_active}">${x.is_active?'Deactivate':'Activate'}</button></div>`).join('')||'<div class="muted">No authorized users yet.</div>')}
async function toggle(b){b.disabled=true;const next=b.dataset.active!=='true';const r=await sb.from('user_access_grants').update({is_active:next,updated_at:new Date().toISOString()}).eq('id',b.dataset.id);if(r.error){alert(r.error.message);b.disabled=false}else{await users();window.WinTurboRefreshPendingChannelUsersV38?.()}}
document.addEventListener('click',e=>{const b=e.target.closest?.('.toggleUserV40');if(b)toggle(b)});async function run(){removeOld();await telegram();await users()}window.WinTurboRefreshVerificationV40=run;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,1100),{once:true});else setTimeout(run,1100)})();</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8')