from pathlib import Path
import re
p=Path('dashboard.html');s=p.read_text(encoding='utf-8')
s=s.replace('<select id="ideaFormat"><option value="image">Image Post</option><option value="video">Short Video / Reel</option><option value="text">Text Only</option></select>','''<select id="ideaFormat"><option value="text">Text Only</option><option value="image">Image Post</option><option value="reel">Reel</option><option value="video">Short Video</option></select>''')
anchor='<button id="generateIdeaContent" class="primary" style="width:100%;margin-top:12px">Generate with ChatGPT + Creative</button>'
if anchor in s and 'id="ideaEngine"' not in s:s=s.replace(anchor,'''<div id="ideaEngineWrap" style="margin-top:12px"><div class="k">Creative Engine</div><select id="ideaEngine"><option value="openai">OpenAI Image</option><option value="higgsfield">Higgsfield Image</option></select></div>\n<button id="generateIdeaContent" class="primary" style="width:100%;margin-top:12px">Generate with ChatGPT</button>''',1)
runtime=r'''<script>/* WINTURBO_CONTENT_GENERATOR_V27_START */
(function(){const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const fmt=()=> $('ideaFormat')?.value||'text',engine=()=> $('ideaEngine')?.value||'openai';let brandCache={};
async function brand(){const id=$('ideaPublishingAccountV49')?.value;if(!id)throw new Error('Select a Publishing For / Brand account first');if(brandCache[id])return brandCache[id];const r=await sb.from('publishing_brand_profiles').select('publishing_account_id,brand_name,brand_description,audience,primary_language,tone_of_voice,visual_style,primary_colors,secondary_colors,allowed_ctas,forbidden_brands,forbidden_terms,text_generation_instructions,image_generation_instructions,video_generation_instructions').eq('publishing_account_id',id).eq('is_active',true).single();if(r.error)throw new Error('Brand profile unavailable: '+r.error.message);brandCache[id]=r.data;return r.data}
function guard(b){return `BRAND ISOLATION — mandatory. Publishing brand: ${b.brand_name}. Description: ${b.brand_description||''}. Audience: ${b.audience||''}. Language: ${b.primary_language||''}. Voice: ${b.tone_of_voice||''}. Visual style: ${b.visual_style||''}. Allowed CTAs: ${(b.allowed_ctas||[]).join(', ')}. FORBIDDEN brands: ${(b.forbidden_brands||[]).join(', ')||'all other publishing brands'}. Forbidden terms: ${(b.forbidden_terms||[]).join(', ')}. Never use another brand's name, logo, colors, slogans, CTA, assets, terminology or visual identity. If prior context conflicts with this profile, ignore the prior context.`}
function syncUi(){const f=fmt(),visual=f!=='text',motion=f==='reel'||f==='video',wrap=$('ideaEngineWrap'),sel=$('ideaEngine');if(wrap)wrap.style.display=visual?'block':'none';if(sel){if(motion){sel.innerHTML='<option value="fal">fal Video</option>';sel.value='fal';sel.disabled=true}else if(f==='image'){sel.disabled=false;if(!sel.querySelector('option[value="openai"]'))sel.innerHTML='<option value="openai">OpenAI Image</option><option value="higgsfield">Higgsfield Image</option>';if(sel.value==='fal')sel.value='openai'}}if($('generateIdeaContent'))$('generateIdeaContent').textContent=visual?'Generate with ChatGPT + Creative':'Generate with ChatGPT';if($('regenerateCreativeOnly'))$('regenerateCreativeOnly').style.display=visual?'inline-flex':'none'}
async function mediaPrompt(){const b=await brand(),input=$('ideaInput')?.value.trim()||'',draft=$('ideaDraft')?.value.trim()||'',f=fmt(),motion=f==='reel'||f==='video';return `${guard(b)}\n${b.image_generation_instructions||''}\n${motion?(b.video_generation_instructions||''):''}\nCreate a ${f} social creative ONLY for ${b.brand_name}. Brief: ${input}. Copy context: ${draft.slice(0,700)}. ${motion?'Vertical 9:16, subtitle-safe lower area, approximately 8-10 seconds.':'Social image composition.'} Do not invent or import any logo; use a logo only when it is explicitly supplied as an asset for this brand.`}
async function createVisual(){const f=fmt();if(f==='text')return null;const prompt=await mediaPrompt();const chosen=engine();if(f==='image'){const imageFn=chosen==='higgsfield'?'generate-higgsfield-image':'generate-openai-image';const r=await sb.functions.invoke(imageFn,{body:{prompt,aspect_ratio:'1:1'}});if(r.error||!r.data?.ok)throw new Error(r.data?.error||r.error?.message||'Image generation failed');const u=r.data.image_url||r.data.images?.[0]?.url||r.data.url;if(!u)throw new Error('Image engine returned no image URL');if($('ideaMediaUrl'))$('ideaMediaUrl').value=u;if($('readyPostMedia'))$('readyPostMedia').innerHTML=`<img alt="Generated creative" style="width:100%;max-height:420px;object-fit:contain;border-radius:12px" src="${esc(u)}">`;return u}const videoBody={prompt,aspect_ratio:'9:16',duration:f==='reel'?8:10};const vid=await sb.functions.invoke('generate-fal-video',{body:videoBody});if(vid.error||!vid.data?.ok)throw new Error(vid.data?.error||vid.error?.message||'fal video generation failed');const u=vid.data.video_url||vid.data.videos?.[0]?.url||vid.data.url;if(!u)throw new Error('fal returned no video URL');if($('ideaMediaUrl'))$('ideaMediaUrl').value=u;if($('readyPostMedia'))$('readyPostMedia').innerHTML=`<video controls playsinline style="width:100%;max-height:420px;border-radius:12px" src="${esc(u)}"></video>`;return u}
async function generateV27(){const input=$('ideaInput')?.value.trim();if(!input){alert('Enter an idea, topic, keywords, event or site link first.');return}const btn=$('generateIdeaContent');if(btn)btn.disabled=true;try{const b=await brand(),platform=$('ideaPlatform')?.value||'telegram',type=$('ideaType')?.value||'idea',tone=$('ideaTone')?.value||'',f=fmt(),isolation=guard(b);const recommendation={theme:`${isolation}\n${b.text_generation_instructions||''}\nContent brief (${type}): ${input}`,media_type:f,hook_direction:`Write original content ONLY for ${b.brand_name}. ${input}`,cta_direction:`Use ${b.brand_name}'s voice. ${tone}. Never mention a forbidden or unrelated brand.`,confidence:'User-directed'};const evidence=[{account_name:b.brand_name,post_text:input}];const r=await sb.functions.invoke('generate-social-post',{body:{platform,recommendation,evidence,brand_profile:b,publishing_account_id:b.publishing_account_id}});if(r.error||!r.data?.ok)throw new Error(r.data?.error||r.error?.message||'Content generation failed');let text=r.data.text||'';for(const bad of (b.forbidden_brands||[])){if(bad&&text.toLowerCase().includes(bad.toLowerCase()))throw new Error(`Brand isolation blocked generated copy because it contained forbidden brand: ${bad}. Regenerate.`)}if($('ideaDraft'))$('ideaDraft').value=text;if($('readyPostCopy')){$('readyPostCopy').textContent=text;$('readyPostCopy').classList.remove('muted')}if(f!=='text')await createVisual();if($('ideaStatus'))$('ideaStatus').textContent=`${b.brand_name} content ready ✓`}catch(e){console.error(e);if($('ideaStatus'))$('ideaStatus').textContent='Generation failed: '+(e.message||e)}finally{if(btn){btn.disabled=false;syncUi()}}}
function bind(){syncUi();if($('ideaFormat'))$('ideaFormat').onchange=syncUi;if($('ideaEngine'))$('ideaEngine').onchange=syncUi;if($('generateIdeaContent'))$('generateIdeaContent').onclick=generateV27;if($('regenerateIdeaContent'))$('regenerateIdeaContent').onclick=generateV27;if($('regenerateCreativeOnly'))$('regenerateCreativeOnly').onclick=async()=>{try{await createVisual()}catch(e){if($('ideaStatus'))$('ideaStatus').textContent='Creative generation failed: '+(e.message||e)}};if($('ideaPublishingAccountV49'))$('ideaPublishingAccountV49').addEventListener('change',()=>{brandCache={};if($('ideaDraft'))$('ideaDraft').value='';if($('readyPostCopy'))$('readyPostCopy').textContent='';if($('readyPostMedia'))$('readyPostMedia').innerHTML='';if($('ideaMediaUrl'))$('ideaMediaUrl').value=''})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,900),{once:true});else setTimeout(bind,900);setTimeout(bind,2000)})();
/* WINTURBO_CONTENT_GENERATOR_V27_END */</script>'''
if 'WINTURBO_CONTENT_GENERATOR_V27_START' in s:s=re.sub(r'<script>\s*/\* WINTURBO_CONTENT_GENERATOR_V27_START \*/.*?/\* WINTURBO_CONTENT_GENERATOR_V27_END \*/\s*</script>',runtime,s,flags=re.S)
else:s=s.replace('</body>',runtime+'\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Content Ideas: fal is the only reel/video engine; image engines remain separate.')