from pathlib import Path
import re

p = Path('dashboard.html')
s = p.read_text()

# Growth Analytics v3: focus on measurable posting frequency/timing, not immature follower deltas.
new_growth = '''<section id="growth" class="section"><div class="grid4"><div class="card"><div class="k">Largest Audience</div><div id="growthTop" class="v" style="font-size:19px">—</div><div id="growthTopSub" class="subv">—</div></div><div class="card"><div class="k">Highest Posting Frequency · 7D</div><div id="mostActive7d" class="v" style="font-size:19px">—</div><div id="mostActive7dSub" class="subv">—</div></div><div class="card"><div class="k">Most Common Posting Time</div><div id="commonPostTime" class="v" style="font-size:19px">—</div><div id="commonPostTimeSub" class="subv">—</div></div><div class="card"><div class="k">Highest Avg Views · 7D</div><div id="bestAvgViews7d" class="v" style="font-size:19px">—</div><div id="bestAvgViews7dSub" class="subv">—</div></div></div><div class="card"><div class="sectionHead"><div><h3>Measured Competitor Performance</h3><div class="muted small">Publicly observable posting frequency, timing and view performance from the latest available 7-day window.</div></div><span id="growthUpdated" class="pill">2-HOUR REFRESH</span></div><div class="tableWrap"><table><thead><tr><th>Audience Rank</th><th>Competitor</th><th>Audience</th><th>Posts Today</th><th>Posts / Day · 7D</th><th>Active Days · 7D</th><th>Most Common Posting Time · IST</th><th>Posts at Peak Hour</th><th>Avg Views · 7D</th><th>Median Views · 7D</th><th>Avg View Rate</th><th>Reaction Data</th><th>Tracking Coverage</th></tr></thead><tbody id="growthBody"></tbody></table></div></div></section>'''
s = re.sub(r'<section id="growth" class="section">.*?</section>\n<section id="creative"', new_growth + '\n<section id="creative"', s, count=1, flags=re.S)

s = s.replace("sb.from('competitor_growth_analytics_v2')", "sb.from('competitor_growth_analytics_v3')")
s = s.replace("sb.from('competitor_growth_analytics')", "sb.from('competitor_growth_analytics_v3')")

new_render = r'''function renderGrowth(){const rows=filterByHandle(allGrowth),ranked=[...rows].sort((a,b)=>Number(b.followers_current||0)-Number(a.followers_current||0)),active=[...rows].filter(x=>Number(x.avg_posts_per_day_7d||0)>0).sort((a,b)=>Number(b.avg_posts_per_day_7d||0)-Number(a.avg_posts_per_day_7d||0))[0],bestViews=[...rows].filter(x=>x.avg_views_7d!=null).sort((a,b)=>Number(b.avg_views_7d)-Number(a.avg_views_7d))[0],common=[...rows].filter(x=>x.posts_at_most_common_hour_7d!=null).sort((a,b)=>Number(b.posts_at_most_common_hour_7d)-Number(a.posts_at_most_common_hour_7d))[0],top=ranked[0];$('growthTop').textContent=top?.account_name||'—';$('growthTopSub').textContent=top?fmt.format(top.followers_current||0)+' observed members':'—';$('mostActive7d').textContent=active?.account_name||'No posts yet';$('mostActive7dSub').textContent=active?Number(active.avg_posts_per_day_7d||0).toFixed(2)+' posts/day · '+fmt.format(active.posts_7d||0)+' posts in 7D':'—';$('commonPostTime').textContent=common?.most_common_post_time_ist||'No timing data';$('commonPostTimeSub').textContent=common?common.account_name+' · '+fmt.format(common.posts_at_most_common_hour_7d||0)+' posts at this hour':'—';$('bestAvgViews7d').textContent=bestViews?.account_name||'No view data yet';$('bestAvgViews7dSub').textContent=bestViews?fmt.format(Math.round(Number(bestViews.avg_views_7d)))+' avg views across '+fmt.format(bestViews.posts_with_views_7d||0)+' posts':'—';$('growthBody').innerHTML=rows.length?rows.map(r=>{const reaction=Number(r.posts_7d||0)>0?(Number(r.posts_with_reactions_7d||0)>0?`${Number(r.reaction_visibility_pct||0).toFixed(0)}% posts visible`:'Not publicly visible'):'—',tracking=`${fmt.format(r.snapshot_count||0)} snapshots${r.tracking_hours!=null?` · ${Number(r.tracking_hours).toFixed(1)}h`:''}`;return `<tr><td>#${r.audience_rank}</td><td><b>${esc(r.account_name)}</b><div class="muted small">@${esc(r.handle)}</div></td><td>${r.followers_current==null?'—':fmt.format(r.followers_current)}</td><td>${fmt.format(r.posts_today||0)}</td><td><b>${Number(r.avg_posts_per_day_7d||0).toFixed(2)}</b><div class="muted small">${fmt.format(r.posts_7d||0)} total</div></td><td>${fmt.format(r.active_post_days_7d||0)} / 7</td><td>${esc(r.most_common_post_time_ist||'—')}</td><td>${r.posts_at_most_common_hour_7d==null?'—':fmt.format(r.posts_at_most_common_hour_7d)}</td><td>${r.avg_views_7d==null?'—':fmt.format(Math.round(Number(r.avg_views_7d)))}</td><td>${r.median_views_7d==null?'—':fmt.format(Math.round(Number(r.median_views_7d)))}</td><td>${r.avg_view_rate_7d_pct==null?'—':Number(r.avg_view_rate_7d_pct).toFixed(2)+'%'}</td><td>${reaction}</td><td>${tracking}</td></tr>`}).join(''):'<tr><td colspan="13" class="muted">No measurable competitor data for this selection.</td></tr>'}'''
s = re.sub(r'function renderGrowth\(\)\{.*?\}\nfunction renderCreative\(\)', new_render + '\nfunction renderCreative()', s, count=1, flags=re.S)

# Two-hour cadence in dashboard copy and client refresh.
s = s.replace('<div class="card"><div class="k">Scrape Cycle</div><div class="v" style="font-size:19px">Hourly</div></div>', '<div class="card"><div class="k">Scrape & Analytics Cycle</div><div class="v" style="font-size:19px">Every 2 Hours</div><div class="subv">Data Quality + AI refresh together</div></div>')
s = s.replace('The hourly scraper will backfill up to the last 7 days where available, then keep accumulating.', 'The 2-hour scraper will backfill up to the last 7 days where available, then keep accumulating.')
s = re.sub(r'async function refreshGrowth\(\)\{.*?setInterval\(refreshGrowth,30\*60\*1000\);', "async function refreshAnalytics(){await Promise.all([loadAccounts(),loadGrowth(),loadCreative(),loadSources(),loadSuccess()]);renderAll()}setInterval(refreshAnalytics,2*60*60*1000);", s, count=1, flags=re.S)

# Expand AI recommendation volume.
s = s.replace('.slice(0,6)}\nfunction renderRecommendations()', '.slice(0,18)}\nfunction renderRecommendations()')

# Upgrade success intelligence header with show-more control.
s = re.sub(r'<div class="card" style="margin-bottom:13px"><div class="sectionHead"><div><h3>Likely to Be Successful — AI Intelligence</h3>.*?<div id="successIntelligence" class="successGrid"><div class="muted">Loading success intelligence…</div></div></div>', '''<div class="card" style="margin-bottom:13px"><div class="sectionHead"><div><h3>Likely to Be Successful — AI Intelligence</h3><div class="muted small">15+ evidence-based ideas from the last 7 days, with Telegram, Instagram and Higgsfield image actions.</div></div><div class="recActions"><span class="successBadge">SUCCESS INTELLIGENCE</span><button id="moreSuccessBtn" class="ghost">Show 15 More</button></div></div><div id="successIntelligence" class="successGrid"><div class="muted">Loading success intelligence…</div></div></div>''', s, count=1, flags=re.S)

if 'let successVisible=15;' not in s:
    s = s.replace('let audienceChart,timingChart,allAccounts=[],allGrowth=[],allCreative=[],allSources=[],allSuccess=[];', 'let audienceChart,timingChart,allAccounts=[],allGrowth=[],allCreative=[],allSources=[],allSuccess=[];let successVisible=15;')

success_logic = r'''async function generateSuccessPost(i,channel,button){const r=(window.successRows||[])[i];if(!r)return;const old=button?.textContent;if(button){button.disabled=true;button.textContent='Generating…'}$('postModalTitle').textContent=`${channel} AI Draft · ${r.account_name||'Recommendation'}`;$('postModalSub').textContent='Generating fresh copy from this observed success pattern…';$('generatedPost').value='Generating with AI…';$('postModal').classList.remove('hide');const recommendation={best_time_ist:r.posted_at?timeFmt(r.posted_at):'Use the strongest observed timing window',theme:r.theme||'General',media_type:r.media_type||'image',hook_direction:r.hook||r.post_text||'Direct attention-grabbing opening',cta_direction:'Use a clear, accurate action-led CTA.',avg_views:r.views||null,avg_creative_score:r.success_likelihood_score||null,confidence:r.confidence||'Medium'};const evidence=[{account_name:r.account_name,handle:r.handle,post_text:r.post_text,hook:r.hook,views:r.views,creative_score:r.success_likelihood_score}];try{const{data,error}=await sb.functions.invoke('generate-social-post',{body:{platform:channel.toLowerCase(),recommendation,evidence}});if(error)throw error;if(data?.error)throw new Error(data.error);$('generatedPost').value=data?.text||'No content returned.';$('postModalSub').textContent=`Fresh ${channel} copy generated from this success pattern.`}catch(e){$('generatedPost').value=`AI generation is not available yet. ${e?.message||'Please check the server-side AI configuration.'}`}finally{if(button){button.disabled=false;button.textContent=old}}}
function generateHiggsfieldImage(i){const r=(window.successRows||[])[i];if(!r)return;const platform='Instagram/Telegram';const prompt=`Create a premium social-media image for ${platform}. Theme: ${r.theme||'high-performing social content'}. Core idea: ${(r.hook||r.post_text||'strong visual-first post').slice(0,220)}. Format: ${r.media_type||'image'}. Make it polished, high-contrast, mobile-first and brand-safe. Do not invent performance claims or financial guarantees. Leave clean space for a short headline and CTA.`;navigator.clipboard?.writeText(prompt);$('postModalTitle').textContent='Higgsfield Image Brief';$('postModalSub').textContent='Prompt copied. Higgsfield opens in a new tab; paste the brief to generate the image.';$('generatedPost').value=prompt;$('postModal').classList.remove('hide');window.open('https://higgsfield.ai/ai-image','_blank','noopener')}
function renderSuccess(){if(!$('successIntelligence'))return;let rows=filterByHandle(allSuccess).sort((a,b)=>Number(b.success_likelihood_score||0)-Number(a.success_likelihood_score||0));rows=rows.slice(0,Math.max(15,successVisible));window.successRows=rows;if(!rows.length){$('successIntelligence').innerHTML='<div class="muted">No last-7-day intelligence is available yet for this selection.</div>';return}$('successIntelligence').innerHTML=rows.map((r,i)=>`<div class="successCard"><div class="successHead"><div><span class="successBadge">${Number(r.success_likelihood_score)>=75?'LIKELY TO BE SUCCESSFUL':'PROMISING PATTERN'}</span><h3 style="margin:10px 0 2px">${esc(r.theme||'Unclassified')}</h3><div class="muted small">${esc(r.account_name)} · ${esc(r.media_type||'text')} · ${dateFmt(r.posted_at)}</div></div><div class="successScore">${Number(r.success_likelihood_score||0).toFixed(0)}</div></div><div class="recLine"><b>Content signal:</b> ${esc((r.hook||r.post_text||'Media-led content').slice(0,140))}</div><div class="recLine"><b>Why:</b> ${esc(r.rationale||'Strong observed recent evidence.')}</div><div class="recMeta"><span class="pill">${esc(r.confidence||'Directional')} confidence</span><span class="pill blue">${fmt.format(r.views||0)} views</span><span class="pill orange">${r.observed_view_rate_pct==null?'View rate n/a':Number(r.observed_view_rate_pct).toFixed(2)+'% view rate'}</span></div><div class="small muted">Pattern evidence: ${r.pattern_sample_size||0} posts · ${r.pattern_competitors||0} competitor(s). Directional intelligence, not a guarantee.</div><div class="recActions"><button class="mini" onclick="generateSuccessPost(${i},'Telegram',this)">Generate Telegram</button><button class="mini" onclick="generateSuccessPost(${i},'Instagram',this)">Generate Instagram</button><button class="mini" onclick="generateHiggsfieldImage(${i})">Generate Image · Higgsfield</button><a class="mini" target="_blank" rel="noopener" href="${esc(r.post_url)}">Source</a></div></div>`).join('')}'''
s = re.sub(r'function renderSuccess\(\)\{.*?\}\nfunction renderSources\(\)', success_logic + '\nfunction renderSources()', s, count=1, flags=re.S)

# Bind the show-more button safely after DOM is ready.
if "moreSuccessBtn').onclick" not in s:
    s = s.replace("$('saveSource').onclick=async()=>{", "if($('moreSuccessBtn'))$('moreSuccessBtn').onclick=()=>{successVisible+=15;renderSuccess()};\n$('saveSource').onclick=async()=>{")

p.write_text(s)
print('dashboard v3 patched')
