from pathlib import Path
import re
p=Path('dashboard.html');s=p.read_text(encoding='utf-8')
js=r'''<script>/* WINTURBO_CONTENT_CHANNEL_APPROVAL_V46 */
(function(){
 const $=x=>document.getElementById(x),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));let channels=[];
 function mediaType(){const f=$('ideaFormat')?.value||'text';return f==='reel'||f==='video'?'video':f==='image'?'image':'text'}
 async function loadAuthorized(){const u=(await sb.auth.getUser()).data?.user;if(!u)return[];const pr=await sb.from('profiles').select('role').eq('id',u.id).maybeSingle();const isAdmin=pr.data?.role==='admin';let ids=[];if(!isAdmin){const a=await sb.from('user_publishing_account_access').select('publishing_account_id').eq('user_id',u.id).eq('is_active',true).eq('can_create',true).eq('can_submit_for_approval',true);if(a.error)throw a.error;ids=(a.data||[]).map(x=>x.publishing_account_id);if(!ids.length)return[]}let q=sb.from('publishing_accounts').select('id,platform,account_name,username,connection_status').eq('is_active',true).eq('connection_status','connected').in('platform',['telegram','instagram']);if(!isAdmin)q=q.in('id',ids);const p=await q;if(p.error)throw p.error;return p.data||[]}
 function findHost(){const ready=$('readyPostCopy');return ready?(ready.closest('.card')||ready.parentElement):null}
 function ensure(){const host=findHost();if(!host)return false;let d=$('channelApprovalV46');if(!d){d=document.createElement('div');d.id='channelApprovalV46';d.style='margin-top:16px;padding-top:14px;border-top:1px solid var(--line)';d.innerHTML='<div class="k">SEND FOR POSTING APPROVAL</div><div id="channelApprovalListV46" class="muted small" style="margin-top:8px">Loading selected publishing account…</div><div id="channelApprovalMsgV46" class="muted small" style="margin-top:8px"></div>';host.appendChild(d)}render();return true}
 async function render(){const box=$('channelApprovalListV46');if(!box)return;try{channels=await loadAuthorized();const selected=$('ideaPublishingAccountV49')?.value;if(!selected){box.innerHTML='Select a Publishing For / Brand account above first.';return}const c=channels.find(x=>x.id===selected);if(!c){box.innerHTML='The selected publishing account is not connected or not authorized for this user.';return}box.innerHTML=`<button type="button" class="primary sendApprovalV46" data-id="${c.id}" style="display:inline-block!important;visibility:visible!important;opacity:1!important;margin:4px 6px 4px 0">Send to ${esc(c.account_name)} for ${c.platform==='telegram'?'Telegram':'Instagram'} Approval</button><div class="muted small" style="margin-top:6px">Destination locked to @${esc(c.username||c.account_name)} · ${esc(c.id)}</div>`}catch(e){box.textContent='Unable to load selected publishing account: '+(e.message||e)}}
 async function submit(c){const u=(await sb.auth.getUser()).data?.user;if(!u)throw new Error('Sign in required');const selected=$('ideaPublishingAccountV49')?.value;if(!selected||selected!==c.id)throw new Error('Publishing destination changed. Please review the selected brand and try again.');const fresh=channels.find(x=>x.id===selected);if(!fresh)throw new Error('Selected publishing account is unavailable');const text=$('ideaDraft')?.value?.trim()||$('readyPostCopy')?.textContent?.trim()||'';if(!text)throw new Error('Generate content first');const media=$('ideaMediaUrl')?.value||null;const r=await sb.from('publishing_queue').insert({platform:fresh.platform,publishing_account_id:fresh.id,content_text:text,media_url:media,media_type:mediaType(),status:'draft',created_by:u.id,requested_by:u.id}).select('id,publishing_account_id').single();if(r.error)throw r.error;if(r.data?.publishing_account_id!==selected)throw new Error('Destination verification failed; item was not accepted.');return r.data}
 async function send(id){const m=$('channelApprovalMsgV46');if(m)m.textContent='Sending to selected account for approval…';const c=channels.find(x=>x.id===id);if(!c){if(m)m.textContent='Could not send: selected account unavailable';return}try{await submit(c);if(m)m.textContent=`Sent for approval ✓ ${c.account_name} (@${c.username||''})`}catch(e){if(m)m.textContent='Could not send: '+(e.message||e)}}
 document.addEventListener('click',e=>{const b=e.target.closest?.('.sendApprovalV46');if(b){e.preventDefault();send(b.dataset.id)}else if(e.target?.dataset?.s==='contentIdeas'){setTimeout(ensure,120)}});
 document.addEventListener('change',e=>{if(e.target?.id==='ideaPublishingAccountV49')render()});
 function init(){ensure();setTimeout(ensure,500);setTimeout(ensure,1500)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();</script>'''
pat=r'<script>/\* WINTURBO_CONTENT_CHANNEL_APPROVAL_V46 \*/.*?</script>'
if re.search(pat,s,flags=re.S): s=re.sub(pat,js,s,count=1,flags=re.S)
else: s=s.replace('</body>',js+'\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Content approval destination is strictly locked to selected publishing account, including admin.')