from pathlib import Path
p=Path('dashboard.html');s=p.read_text(encoding='utf-8');M='WINTURBO_BRAND_CHANNEL_CONTENT_V49'
# Replace the previously generated v49 runtime if present; otherwise append it.
import re
js=r'''<script>/* WINTURBO_BRAND_CHANNEL_CONTENT_V49 */
(function(){const $=id=>document.getElementById(id);let accounts=[];
async function load(){try{const u=(await sb.auth.getUser()).data?.user;if(!u)return;const a=await sb.from('user_publishing_account_access').select('publishing_account_id').eq('user_id',u.id).eq('is_active',true).eq('can_create',true);const ids=(a.data||[]).map(x=>x.publishing_account_id);if(!ids.length)return;const p=await sb.from('publishing_accounts').select('id,platform,account_name,username,connection_status').in('id',ids).eq('is_active',true);accounts=(p.data||[]).filter(x=>x.connection_status==='connected');mount()}catch(e){console.warn('v49 account load',e)}}
function mount(){const input=$('ideaInput');if(!input||$('ideaPublishingAccountV49')||!accounts.length)return;const w=document.createElement('div');w.style='margin-bottom:12px';w.innerHTML='<div class="k">PUBLISHING FOR / BRAND</div><select id="ideaPublishingAccountV49"></select><div id="ideaBrandNoteV49" class="muted small" style="margin-top:6px"></div>';input.parentElement.insertBefore(w,input);const sel=$('ideaPublishingAccountV49');sel.innerHTML=accounts.map(a=>`<option value="${a.id}">${a.account_name} · ${a.platform.toUpperCase()}</option>`).join('');sel.onchange=sync;sync()}
function selected(){return accounts.find(a=>a.id===$('ideaPublishingAccountV49')?.value)||accounts[0]}
function sync(){const a=selected(),note=$('ideaBrandNoteV49');if(!a||!note)return;note.textContent=`All copy, images and videos will be generated for ${a.account_name} and routed to ${a.account_name} for approval.`;document.querySelectorAll('.sendApprovalV46').forEach(b=>{const on=b.dataset.id===a.id;b.style.display=on?'':'none';if(on)b.textContent=`Send to ${a.account_name} for Approval`});const all=$('sendAllApprovalV46');if(all)all.style.display='none'}
function brandPrompt(base){const a=selected();if(!a)return base;let identity=a.account_name;if((a.username||'').toLowerCase()==='thegreatraka')identity='The Great Raka — independent creator-led betting/gaming advice channel. Do not mention WinTurbo unless explicitly requested.';else if((a.account_name||'').toLowerCase().includes('winturbo'))identity='WinTurbo — gaming platform brand; bold premium Gen-Z Indian gaming voice.';return `${base}\nPublishing destination and brand identity: ${identity}\nWrite only for this selected brand/account.`}
function wrap(){if(window.__v49Wrapped)return;window.__v49Wrapped=true;const original=sb.functions.invoke.bind(sb.functions);sb.functions.invoke=async function(name,opts={}){if(['generate-social-post','generate-openai-image','generate-higgsfield-image','generate-higgsfield-video'].includes(name)&&$('ideaPublishingAccountV49')){opts={...opts,body:{...(opts.body||{})}};if(name==='generate-social-post'){const r=opts.body.recommendation||{};opts.body.recommendation={...r,theme:brandPrompt(r.theme||''),hook_direction:brandPrompt(r.hook_direction||''),cta_direction:brandPrompt(r.cta_direction||'')}}else if(opts.body.prompt)opts.body.prompt=brandPrompt(opts.body.prompt)}return original(name,opts)}}
wrap();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(load,600),{once:true});else setTimeout(load,600);setTimeout(load,1800);document.addEventListener('click',e=>{if(e.target?.dataset?.s==='contentIdeas')setTimeout(()=>{mount();sync()},150)})})();</script>'''
pat=r'<script>/\* WINTURBO_BRAND_CHANNEL_CONTENT_V49 \*/.*?</script>'
if re.search(pat,s,flags=re.S): s=re.sub(pat,js,s,count=1,flags=re.S)
else: s=s.replace('</body>',js+'\n</body>',1)
p.write_text(s,encoding='utf-8')