from pathlib import Path
p=Path('dashboard.html'); s=p.read_text(encoding='utf-8')
MARK='WINTURBO_CHANNEL_WORKFLOW_V35_START'
if MARK in s: print('v35 already present'); raise SystemExit
css='''/* WINTURBO_CHANNEL_WORKFLOW_V35_CSS */
.channelConnectGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.channelCard{padding:13px;border:1px solid var(--line);border-radius:12px;background:#0b110d}.channelAccessBadge{font-size:10px;padding:4px 7px;border-radius:999px;background:#17301e;color:#83f19b}.channelPicker{margin:8px 0}.scopedApproval{border-left:3px solid var(--green)}@media(max-width:900px){.channelConnectGrid{grid-template-columns:1fr}}'''
s=s.replace('</style>',css+'\n</style>',1)
verification='''<div id="channelVerificationV35" class="card" style="margin-top:14px"><div class="sectionHead"><div><h3>Publishing Channel Verification</h3><div class="muted small">Link multiple Telegram / Instagram destinations. Admins authorize each destination independently to one or more users.</div></div><span class="pill blue">MULTI-CHANNEL</span></div><div id="channelVerificationList" class="channelConnectGrid"><div class="muted">Loading linked channels…</div></div><div class="muted small" style="margin-top:10px">Telegram channels become publishable only after the bot/integration is connected and the user has explicit account access. Instagram remains approval-only until its publishing integration is connected.</div></div>'''
pos=s.find('</section>',s.find('id="verification"'))
if pos>=0:s=s[:pos]+verification+s[pos:]
js=r'''<script>
/* WINTURBO_CHANNEL_WORKFLOW_V35_START */
(function(){
 const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); let me,role,allowed=[];
 async function identity(){const u=await sb.auth.getUser();me=u.data.user;if(!me)return;const p=await sb.from('profiles').select('role').eq('id',me.id).maybeSingle();role=p.data?.role;const g=await sb.from('user_publishing_account_access').select('*').eq('user_id',me.id).eq('is_active',true);allowed=g.data||[];window.WINTURBO_PUBLISHING_ACCESS=allowed}
 async function renderVerification(){const h=$('channelVerificationList');if(!h)return;const r=await sb.from('publishing_accounts').select('*').eq('is_active',true).order('platform').order('account_name');const rows=r.data||[];h.innerHTML=rows.length?rows.map(a=>{const g=role==='admin'?{can_publish:true}:allowed.find(x=>x.publishing_account_id===a.id);return `<div class="channelCard" data-publishing-account-id="${a.id}"><div><b>${esc(a.account_name||a.username)}</b> <span class="channelAccessBadge">${esc(a.platform)}</span></div><div class="muted small">${esc(a.username||a.external_account_id||'')} · ${esc(a.connection_status||'not connected')}</div><div class="small" style="margin-top:8px">${role==='admin'?'Admin managed':g?'Authorized for you':'Not authorized for you'}</div></div>`}).join(''):'<div class="muted">No publishing channels linked yet.</div>'}
 function authorizedTargets(platform){return Array.from(document.querySelectorAll('option[data-publishing-account-id]')).filter(o=>{const a=o.dataset.publishingAccountId;if(role==='admin')return true;const g=allowed.find(x=>x.publishing_account_id===a);return !!(g&&g.can_create&&g.can_submit_for_approval)})}
 async function routeQueuePayload(payload){if(!me)await identity();let accountId=payload.publishing_account_id;if(!accountId){const platform=String(payload.platform||'telegram').toLowerCase();const r=await sb.from('publishing_accounts').select('id,platform,account_name,username').eq('platform',platform).eq('is_active',true);let rows=r.data||[];if(role!=='admin')rows=rows.filter(a=>allowed.some(g=>g.publishing_account_id===a.id&&g.can_create&&g.can_submit_for_approval));if(rows.length===1)accountId=rows[0].id;else if(rows.length>1){accountId=prompt('Choose authorized destination:\n'+rows.map((a,i)=>`${i+1}. ${a.account_name||a.username}`).join('\n'));const n=Number(accountId);accountId=rows[n-1]?.id}if(!accountId)throw new Error('No authorized publishing channel selected. Ask an admin to grant channel access.')}return {...payload,publishing_account_id:accountId,requested_by:me.id,created_by:me.id,status:'draft'}}
 window.WinTurboRouteApprovalV35=routeQueuePayload;
 async function enhanceSelectors(){if(!me)await identity();const r=await sb.from('publishing_accounts').select('id,platform,account_name,username').eq('is_active',true);let rows=r.data||[];if(role!=='admin')rows=rows.filter(a=>allowed.some(g=>g.publishing_account_id===a.id&&g.can_create&&g.can_submit_for_approval));window.WINTURBO_AUTHORIZED_CHANNELS=rows;document.querySelectorAll('select[data-channel-target],#contentPublishingAccount,#recommendationPublishingAccount').forEach(sel=>{sel.innerHTML='<option value="">Select authorized channel</option>'+rows.map(a=>`<option data-publishing-account-id="${a.id}" value="${a.id}">${esc(a.platform)} · ${esc(a.account_name||a.username)}</option>`).join('')})}
 async function scopeApprovals(){if(!me)await identity();const approval=$('approval');if(!approval)return;approval.dataset.channelScoped='1';window.WINTURBO_APPROVAL_SCOPE={user_id:me.id,account_ids:role==='admin'?null:allowed.map(x=>x.publishing_account_id)} }
 async function boot(){await identity();await Promise.all([renderVerification(),enhanceSelectors(),scopeApprovals()])}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot().catch(console.error),{once:true});else boot().catch(console.error)
})();
/* WINTURBO_CHANNEL_WORKFLOW_V35_END */
</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8');print('Added multi-channel verification and user-scoped approval routing.')