from pathlib import Path
p=Path('dashboard.html');s=p.read_text(encoding='utf-8')
MARK='WINTURBO_TELEGRAM_VERIFY_V36_START'
if MARK in s: print('v36 already present');raise SystemExit
css='''/* WINTURBO_TELEGRAM_VERIFY_V36_CSS */
.tgVerifySummary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:12px 0}.tgVerifyCards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.tgVerifyCard{padding:14px;border:1px solid var(--line);border-radius:13px;background:#0b110d}.tgStatus{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:700}.tgConnected{background:#15351e;color:#83f19b}.tgPending{background:#342b12;color:#ffd66b}.tgError{background:#3a1818;color:#ff9292}.tgDot{width:7px;height:7px;border-radius:50%;background:currentColor}.tgMeta{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:10px 0;font-size:11px}.tgVerifyActions{display:flex;gap:7px;flex-wrap:wrap}@media(max-width:800px){.tgVerifySummary,.tgVerifyCards{grid-template-columns:1fr}}'''
s=s.replace('</style>',css+'\n</style>',1)
section='''<div id="telegramVerificationV36" class="card" style="margin-top:14px"><div class="sectionHead"><div><h3>Telegram Connections</h3><div class="muted small">Channel-wise publishing verification. Each Telegram destination has its own connection state.</div></div><button id="verifyAllTelegramV36" class="mini">Verify All</button></div><div id="tgVerifySummaryV36" class="tgVerifySummary"></div><div id="tgVerifyCardsV36" class="tgVerifyCards"><div class="muted">Loading Telegram connections…</div></div></div>'''
pos=s.find('</section>',s.find('id="verification"'))
if pos<0:raise SystemExit('Verification section not found')
s=s[:pos]+section+s[pos:]
js=r'''<script>
/* WINTURBO_TELEGRAM_VERIFY_V36_START */
(function(){const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let rows=[];
function status(a){const x=String(a.connection_status||'pending_verification').toLowerCase();if(x==='connected')return['Connected','tgConnected'];if(['error','failed','disconnected'].includes(x))return['Not Connected','tgError'];return['Pending Verification','tgPending']}
async function load(){const r=await sb.from('publishing_accounts').select('id,platform,account_name,external_account_id,username,is_active,connection_status,updated_at').eq('platform','telegram').eq('is_active',true).order('account_name');rows=r.data||[];render()}
function render(){const connected=rows.filter(a=>String(a.connection_status).toLowerCase()==='connected').length,pending=rows.filter(a=>!['connected','error','failed','disconnected'].includes(String(a.connection_status).toLowerCase())).length,down=rows.length-connected-pending;$('tgVerifySummaryV36').innerHTML=`<div class="channelCard"><b>${rows.length}</b><div class="muted small">Telegram Channels</div></div><div class="channelCard"><b>${connected}</b><div class="muted small">Connected</div></div><div class="channelCard"><b>${pending+down}</b><div class="muted small">Need Verification</div></div>`;$('tgVerifyCardsV36').innerHTML=rows.length?rows.map(a=>{const [label,cls]=status(a);return `<div class="tgVerifyCard" data-id="${a.id}"><div class="pubAccountTop"><div><b>${esc(a.account_name||a.username)}</b><div class="muted small">@${esc(String(a.username||'').replace(/^@/,''))}</div></div><span class="tgStatus ${cls}"><i class="tgDot"></i>${label}</span></div><div class="tgMeta"><span>Channel: ${esc(a.external_account_id||a.username||'—')}</span><span>Checked: ${a.updated_at?new Date(a.updated_at).toLocaleString():'Never'}</span></div><div class="tgVerifyActions"><button class="mini tgVerifyOne" data-id="${a.id}" data-channel="${esc(a.external_account_id||('@'+a.username))}">Verify Connection</button></div><div class="muted small tgVerifyMsg" style="margin-top:7px"></div></div>`}).join(''):'<div class="muted">No Telegram publishing channels configured.</div>'}
async function verify(btn){const card=btn.closest('.tgVerifyCard'),msg=card.querySelector('.tgVerifyMsg'),channel=btn.dataset.channel;btn.disabled=true;msg.textContent='Checking bot admin and post permission…';try{const r=await sb.functions.invoke('publish-telegram',{body:{action:'verify_channel',channel}});if(r.error)throw r.error;const d=r.data||{};msg.textContent=d.connected?`Connected${d.bot?.username?' via @'+d.bot.username:''}. Bot can post.`:(d.error||'Not connected: bot must be an admin with Post Messages permission.');await load()}catch(e){msg.textContent=e.message||String(e)}finally{btn.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest?.('.tgVerifyOne');if(b)verify(b);if(e.target.closest?.('#verifyAllTelegramV36')){document.querySelectorAll('.tgVerifyOne').forEach((x,i)=>setTimeout(()=>verify(x),i*400))}});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>load().catch(console.error),{once:true});else load().catch(console.error)})();
/* WINTURBO_TELEGRAM_VERIFY_V36_END */
</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8');print('Added Telegram channel-wise verification cards.')