from pathlib import Path
p=Path('dashboard.html');s=p.read_text(encoding='utf-8');M='WINTURBO_CHANNEL_USER_ACCESS_V37_START'
# This patch is intentionally idempotent because dashboard.html may already contain v37
# from a previous generated build. A repeated workflow run should continue to later patches.
if M in s:
    print('v37 already present; continuing')
    raise SystemExit(0)
css='''.channelAccessGrid{display:grid;gap:10px;margin-top:12px}.channelAccessRow{display:grid;grid-template-columns:minmax(170px,1.2fr) repeat(5,minmax(85px,.55fr)) 90px;gap:8px;align-items:center;padding:11px;border:1px solid var(--line);border-radius:12px}.channelAccessRow label{font-size:11px}.channelAccessRow input{accent-color:#66e58a}@media(max-width:900px){.channelAccessRow{grid-template-columns:1fr 1fr}}'''
s=s.replace('</style>',css+'\n</style>',1)
card='''<div id="channelUserAccessV37" class="card" style="margin-top:14px"><div class="sectionHead"><div><h3>Channel Posting Access</h3><div class="muted small">Admin assigns exactly which connected Telegram channels each user can create, approve and publish to.</div></div></div><div class="field" style="max-width:420px"><label>User</label><select id="channelAccessUserV37"><option value="">Select authorized user</option></select></div><div id="channelAccessGridV37" class="channelAccessGrid"><div class="muted">Select a user to manage channel access.</div></div></div>'''
vi=s.find('id="verification"')
if vi<0: raise SystemExit('verification section not found')
pos=s.find('</section>',vi)
if pos<0: raise SystemExit('verification section closing tag not found')
s=s[:pos]+card+s[pos:]
js=r'''<script>/* WINTURBO_CHANNEL_USER_ACCESS_V37_START */
(function(){const $=x=>document.getElementById(x);let channels=[],grants=[];async function init(){const sel=$('channelAccessUserV37'),grid=$('channelAccessGridV37');if(!sel||!grid)return;const u=await sb.from('user_access_grants').select('email,user_id,access_level,is_active').eq('is_active',true).not('user_id','is',null).order('email');sel.innerHTML='<option value="">Select authorized user</option>'+((u.data||[]).map(x=>`<option value="${x.user_id}">${x.email} · ${x.access_level}</option>`).join(''));const c=await sb.from('publishing_accounts').select('id,account_name,username,connection_status').eq('platform','telegram').eq('is_active',true).order('account_name');channels=c.data||[]}
async function render(uid){const grid=$('channelAccessGridV37');if(!grid)return;if(!uid){grid.innerHTML='<div class="muted">Select a user to manage channel access.</div>';return}const g=await sb.from('user_publishing_account_access').select('*').eq('user_id',uid);grants=g.data||[];grid.innerHTML=channels.map(c=>{const x=grants.find(z=>z.publishing_account_id===c.id)||{};const connected=c.connection_status==='connected';return `<div class="channelAccessRow" data-account="${c.id}"><div><b>${c.account_name}</b><div class="muted small">@${c.username||''} · ${connected?'Connected':'Not connected'}</div></div><label><input type="checkbox" data-k="is_active" ${x.is_active?'checked':''} ${connected?'':'disabled'}> Access</label><label><input type="checkbox" data-k="can_create" ${x.can_create?'checked':''}> Create</label><label><input type="checkbox" data-k="can_submit_for_approval" ${x.can_submit_for_approval?'checked':''}> Submit</label><label><input type="checkbox" data-k="can_approve" ${x.can_approve?'checked':''}> Approve</label><label><input type="checkbox" data-k="can_publish" ${x.can_publish?'checked':''}> Publish</label><button class="mini saveChannelAccessV37">Save</button></div>`}).join('')||'<div class="muted">No Telegram channels configured.</div>'}
async function save(row){const sel=$('channelAccessUserV37'),uid=sel?.value;if(!uid)return;const obj={user_id:uid,publishing_account_id:row.dataset.account};row.querySelectorAll('[data-k]').forEach(i=>obj[i.dataset.k]=i.checked);const r=await sb.from('user_publishing_account_access').upsert(obj,{onConflict:'user_id,publishing_account_id'});if(r.error)alert(r.error.message);else{const b=row.querySelector('button');b.textContent='Saved ✓';setTimeout(()=>b.textContent='Save',1200)}}
document.addEventListener('change',e=>{if(e.target?.id==='channelAccessUserV37')render(e.target.value)});document.addEventListener('click',e=>{const b=e.target.closest?.('.saveChannelAccessV37');if(b)save(b.closest('.channelAccessRow'))});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(console.error),{once:true});else init().catch(console.error);})();
/* WINTURBO_CHANNEL_USER_ACCESS_V37_END */</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8')