from pathlib import Path
p=Path('dashboard.html');s=p.read_text(encoding='utf-8');M='WINTURBO_CHANNEL_AUTHORIZATION_V43'
if M in s: print('v43 already present'); raise SystemExit(0)
js=r'''<script>/* WINTURBO_CHANNEL_AUTHORIZATION_V43 */
(function(){
 const $=x=>document.getElementById(x); let accounts=[];
 function platformLabel(p){return p==='telegram'?'Telegram':p==='instagram'?'Instagram':(p||'Channel')}
 function statusLabel(c){return c.connection_status==='connected'?'Approved / Connected':'Not Approved'}
 async function loadUsers(){const sel=$('channelAccessUserV37');if(!sel)return;const u=await sb.from('user_access_grants').select('email,user_id,access_level,is_active').eq('is_active',true).order('email');sel.innerHTML='<option value="">Select authorized user</option>'+((u.data||[]).map(x=>`<option value="${x.user_id||''}" ${x.user_id?'':'disabled'}>${x.email} · ${x.access_level}${x.user_id?'':' · Awaiting Login'}</option>`).join(''))}
 async function loadAccounts(){const r=await sb.from('publishing_accounts').select('id,platform,account_name,username,connection_status,is_active').eq('is_active',true).in('platform',['telegram','instagram']).order('platform').order('account_name');accounts=r.data||[]}
 async function render(uid){const grid=$('channelAccessGridV37');if(!grid)return;if(!uid){grid.innerHTML='<div class="muted">Select a user above. You will then see every approved Telegram and Instagram publishing destination and whether this user is authorized to post to it.</div>';return}const g=await sb.from('user_publishing_account_access').select('*').eq('user_id',uid);const grants=g.data||[];grid.innerHTML=accounts.map(c=>{const x=grants.find(z=>z.publishing_account_id===c.id)||{},ok=c.connection_status==='connected';return `<div class="channelAccessRow" data-account="${c.id}" style="grid-template-columns:minmax(220px,1.5fr) repeat(5,minmax(78px,.5fr)) 90px"><div><div style="display:flex;gap:7px;align-items:center;flex-wrap:wrap"><b>${c.account_name}</b><span class="badge">${platformLabel(c.platform)}</span><span class="badge">${statusLabel(c)}</span></div><div class="muted small">${c.username?'@'+c.username:'No username'} · ${x.is_active?'User authorized':'No user access'}</div></div><label><input type="checkbox" data-k="is_active" ${x.is_active?'checked':''} ${ok?'':'disabled'}> Authorize</label><label><input type="checkbox" data-k="can_create" ${x.can_create?'checked':''} ${ok?'':'disabled'}> Create</label><label><input type="checkbox" data-k="can_submit_for_approval" ${x.can_submit_for_approval?'checked':''} ${ok?'':'disabled'}> Submit</label><label><input type="checkbox" data-k="can_approve" ${x.can_approve?'checked':''} ${ok?'':'disabled'}> Approve</label><label><input type="checkbox" data-k="can_publish" ${x.can_publish?'checked':''} ${ok?'':'disabled'}> Post</label><button class="mini saveChannelAccessV43" ${ok?'':'disabled'}>Save</button></div>`}).join('')||'<div class="muted">No approved Telegram or Instagram publishing channels are configured yet.</div>'}
 async function save(row){const uid=$('channelAccessUserV37')?.value;if(!uid)return;const obj={user_id:uid,publishing_account_id:row.dataset.account};row.querySelectorAll('[data-k]').forEach(i=>obj[i.dataset.k]=i.checked);const r=await sb.from('user_publishing_account_access').upsert(obj,{onConflict:'user_id,publishing_account_id'});if(r.error)return alert(r.error.message);const b=row.querySelector('.saveChannelAccessV43');b.textContent='Authorized ✓';setTimeout(()=>b.textContent='Save',1200);render(uid)}
 async function init(){const card=$('channelUserAccessV37');if(!card)return;const h=card.querySelector('h3');if(h)h.textContent='Channel Posting Authorization';const d=card.querySelector('.sectionHead .muted');if(d)d.textContent='Choose a user, then explicitly authorize which approved Telegram or Instagram channel they may create, submit, approve, or post to.';await Promise.all([loadUsers(),loadAccounts()]);render($('channelAccessUserV37')?.value||'')}
 document.addEventListener('change',e=>{if(e.target?.id==='channelAccessUserV37')render(e.target.value)});document.addEventListener('click',e=>{const b=e.target.closest?.('.saveChannelAccessV43');if(b)save(b.closest('.channelAccessRow'))});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1200),{once:true});else setTimeout(init,1200);
})();</script>'''
s=s.replace('</body>',js+'\n</body>',1);p.write_text(s,encoding='utf-8')